### PR TITLE
Attr 2.4.48

### PR DESCRIPTION
**Pull request by avmaisak**
http://wiki.linuxfromscratch.org/lfs/ticket/4308
http://wiki.linuxfromscratch.org/lfs/query?id=4307%2C4308

### CODE REVIEW

**Comment by emmett1** [comment]
i dont know why you remove 'DIST_ROOT=$PKG', i hope you know this package's build script is used with the package manager (https://github.com/emmett1/scratchpkg), so it does use DESTDIR method, install into temporary location before compressed into tar.xz package.

**Comment by avmaisak** [comment]
sorry, typo

**Comment by avmaisak** [comment]
http://www.linuxfromscratch.org/lfs/view/development/chapter06/attr.html

some make options has been changed

**Comment by emmett1** [comment]
Yeah, its ok. Btw i have updated this package. Plus, it use DESTDIR now, not DIST_ROOT anymore. Same for 'acl' package.

**Pull request closed without merging**
