### PR TITLE
packages updates from LFS book dev branch

### PR DESCRIPTION
**Pull request by avmaisak**
http://wiki.linuxfromscratch.org/lfs/ticket/4284

### CODE REVIEW

**Comment by emmett1** [comment]
hey, thanks for the package updates. but please next time make one pull request for one package. i wanna keep it clean, avoiding mess.

**Comment by avmaisak** [comment]
@emmett1 , sorry.

**Comment by emmett1** [comment]
Its ok, no big deal. I'm glad someone helping me update these packages. :)

**Comment by avmaisak** [comment]
@emmett1 while i'm making a translation of the LFS book, i can provide weekly package updates of the book avaliable packages.

**Pull request merged**
